### ISSUE TITLE
Horizontal Mouse Scroll

### ISSUE THREAD

**Issue by eckdev** [oberonamsterdam/react-scrollbooster#3]
i want to use mouse scroll on the horizontal direction. how can i do that?

**Comment by chrisneven** [comment]
Hi @eckdev, I'm not really sure if I understand what you're trying to achieve with react-scrollbooster. The library should be used to create drag-to-scroll components. If you want to scroll horizontally, you could take a look at our other library: https://github.com/oberonamsterdam/horizontal

**Comment by chrisneven** [comment]
If you need more help with an issue relevant to this library you can make a new issue. I'll close this one for now
