### ISSUE TITLE
Is scrollbooster native not supported in React ?

### ISSUE THREAD

**Issue by stuartambient** [oberonamsterdam/react-scrollbooster#5]
Trying to see if I need to use this project.  I've used scrollbooster in the past without any issues, but first time now in a React app and it's not working.

Edit: your code is working for me so I'm happy.

**Comment by chrisneven** [comment]
Hi @stuartambient, thank you for your interest in this library!

To answer your question, I found using the Scrollbooster library with React is perfectly fine. However, you do have more setting up to do and it's more complex to get it working properly. For an example on how to use it, you can take a look at the source code. 

I'm glad to hear that you're using this library and if you have any questions feel free to ask them!
