### ISSUE TITLE
Updated dependencies

### ISSUE THREAD

**Issue by matthew52pickup** [oberonamsterdam/react-scrollbooster#7]
Hello!

I've used this plugin on a project and it's been super useful, so thank you!

I noticed that the scrollbooster dependency isn't up to date, and the version being used on react-scrollbooster has a rather annoying bug that doesn't register click events on mobile/touchscreen. For the time being we've just been updating the dependency manually via FTP after every update, but I figured I'd check in to see if it could be updated in the package to avoid that and save any headaches for future users.

Thanks!

**Comment by chrisneven** [comment]
Hi @matthew52pickup, thank you for using our package! I've updated the dependecies and hopefully it solves this bug and makes your life a little bit easier.

Let me know if I closed this issue too hasty
